[2023-11-23T18:07:41.667+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_successor_task manual__2023-11-23T17:58:01.711169+00:00 [queued]>
[2023-11-23T18:07:41.701+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_successor_task manual__2023-11-23T17:58:01.711169+00:00 [queued]>
[2023-11-23T18:07:41.701+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-23T18:07:41.783+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_successor_task> on 2023-11-23 17:58:01.711169+00:00
[2023-11-23T18:07:41.794+0000] {standard_task_runner.py:57} INFO - Started process 456047 to run task
[2023-11-23T18:07:41.799+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_successor_task', 'manual__2023-11-23T17:58:01.711169+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmptwog889l']
[2023-11-23T18:07:41.803+0000] {standard_task_runner.py:85} INFO - Job 659: Subtask load_successor_task
[2023-11-23T18:07:41.951+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_successor_task manual__2023-11-23T17:58:01.711169+00:00 [running]> on host jarvis
[2023-11-23T18:07:42.453+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_successor_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T17:58:01.711169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T17:58:01.711169+00:00'
[2023-11-23T18:07:42.457+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/utils/load_url.py", line 4, in load_url
    response = requests.get(url)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'dag_SFCrimes_data_bqload': No scheme supplied. Perhaps you meant https://dag_SFCrimes_data_bqload?
[2023-11-23T18:07:42.490+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_successor_task, execution_date=20231123T175801, start_date=20231123T180741, end_date=20231123T180742
[2023-11-23T18:07:42.532+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 659 for task load_successor_task (Invalid URL 'dag_SFCrimes_data_bqload': No scheme supplied. Perhaps you meant https://dag_SFCrimes_data_bqload?; 456047)
[2023-11-23T18:07:42.576+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-23T18:07:42.637+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
