[2023-11-24T22:14:11.054+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [queued]>
[2023-11-24T22:14:11.088+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [queued]>
[2023-11-24T22:14:11.088+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-11-24T22:14:11.161+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): tbl_curated_crime> on 2023-11-24 22:13:04.587401+00:00
[2023-11-24T22:14:11.170+0000] {standard_task_runner.py:57} INFO - Started process 67552 to run task
[2023-11-24T22:14:11.176+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_DimFact', 'tbl_curated_crime', 'manual__2023-11-24T22:13:04.587401+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_DimFact.py', '--cfg-path', '/tmp/tmp0bu9h2ci']
[2023-11-24T22:14:11.180+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask tbl_curated_crime
[2023-11-24T22:14:11.331+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_DimFact.tbl_curated_crime manual__2023-11-24T22:13:04.587401+00:00 [running]> on host jarvis
[2023-11-24T22:14:11.849+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_DimFact' AIRFLOW_CTX_TASK_ID='tbl_curated_crime' AIRFLOW_CTX_EXECUTION_DATE='2023-11-24T22:13:04.587401+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-24T22:13:04.587401+00:00'
[2023-11-24T22:14:11.851+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-24T22:14:11.853+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --select "tag:tbl_curated_crime" --profiles-dir /home/mani-dev/airflow/dags/dbt/dataengineering/profiles --project-dir /home/mani-dev/airflow/dags/dbt/dataengineering']
[2023-11-24T22:14:11.873+0000] {subprocess.py:86} INFO - Output:
[2023-11-24T22:14:11.874+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2023-11-24T22:14:11.875+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-11-24T22:14:11.912+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-11-24T22:14:11.922+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_DimFact, task_id=tbl_curated_crime, execution_date=20231124T221304, start_date=20231124T221411, end_date=20231124T221411
[2023-11-24T22:14:11.973+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 24 for task tbl_curated_crime (Bash command failed. The command returned a non-zero exit code 127.; 67552)
[2023-11-24T22:14:12.033+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-24T22:14:12.103+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
