[2023-12-03T08:27:26.001+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:27:24.325935+00:00 [queued]>
[2023-12-03T08:27:26.031+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:27:24.325935+00:00 [queued]>
[2023-12-03T08:27:26.032+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-12-03T08:27:26.110+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-12-03 08:27:24.325935+00:00
[2023-12-03T08:27:26.121+0000] {standard_task_runner.py:57} INFO - Started process 579141 to run task
[2023-12-03T08:27:26.127+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-12-03T08:27:24.325935+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmp6jukp2i4']
[2023-12-03T08:27:26.131+0000] {standard_task_runner.py:85} INFO - Job 76: Subtask load_to_bq_task
[2023-12-03T08:27:26.298+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-03T08:27:24.325935+00:00 [running]> on host jarvis
[2023-12-03T08:27:26.883+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-03T08:27:24.325935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-03T08:27:24.325935+00:00'
[2023-12-03T08:27:34.767+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/dag_sf_crimes_bqload.py", line 36, in load_bq_raw
    job.result()
  File "/home/mani-dev/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/mani-dev/.local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 2001; errors: 1; max bad: 0; error percent: 0
[2023-12-03T08:27:34.845+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231203T082724, start_date=20231203T082726, end_date=20231203T082734
[2023-12-03T08:27:34.891+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 76 for task load_to_bq_task (400 Error while reading data, error message: CSV processing encountered too many errors, giving up. Rows: 2001; errors: 1; max bad: 0; error percent: 0; 579141)
[2023-12-03T08:27:34.954+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-12-03T08:27:35.006+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
