[2023-11-23T05:53:57.985+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_sf_crimes.download_data_task manual__2023-11-23T05:53:56.873279+00:00 [queued]>
[2023-11-23T05:53:58.026+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_sf_crimes.download_data_task manual__2023-11-23T05:53:56.873279+00:00 [queued]>
[2023-11-23T05:53:58.028+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-23T05:53:58.082+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): download_data_task> on 2023-11-23 05:53:56.873279+00:00
[2023-11-23T05:53:58.091+0000] {standard_task_runner.py:57} INFO - Started process 372482 to run task
[2023-11-23T05:53:58.103+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_sf_crimes', 'download_data_task', 'manual__2023-11-23T05:53:56.873279+00:00', '--job-id', '629', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_raw.py', '--cfg-path', '/tmp/tmpshyria27']
[2023-11-23T05:53:58.108+0000] {standard_task_runner.py:85} INFO - Job 629: Subtask download_data_task
[2023-11-23T05:53:58.281+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_sf_crimes.download_data_task manual__2023-11-23T05:53:56.873279+00:00 [running]> on host jarvis
[2023-11-23T05:53:58.838+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_sf_crimes' AIRFLOW_CTX_TASK_ID='download_data_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T05:53:56.873279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T05:53:56.873279+00:00'
[2023-11-23T05:53:59.642+0000] {socrata.py:63} WARNING - Requests made without an app_token will be subject to strict throttling limits.
[2023-11-23T05:54:00.872+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/curated/dag_sf_crimes_raw.py", line 32, in download_data
    filtered_df.to_csv(dest_file, sep=',', index=False)
  File "/home/mani-dev/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/mani-dev/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/mani-dev/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
  File "/home/mani-dev/.local/lib/python3.10/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_20231123055400.csv'
[2023-11-23T05:54:00.917+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_sf_crimes, task_id=download_data_task, execution_date=20231123T055356, start_date=20231123T055357, end_date=20231123T055400
[2023-11-23T05:54:01.004+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 629 for task download_data_task ([Errno 13] Permission denied: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_20231123055400.csv'; 372482)
[2023-11-23T05:54:01.053+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-23T05:54:01.197+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
