[2023-11-23T18:01:00.206+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-11-23T18:00:58.230597+00:00 [queued]>
[2023-11-23T18:01:00.237+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-11-23T18:00:58.230597+00:00 [queued]>
[2023-11-23T18:01:00.237+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-23T18:01:00.314+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-11-23 18:00:58.230597+00:00
[2023-11-23T18:01:00.323+0000] {standard_task_runner.py:57} INFO - Started process 454893 to run task
[2023-11-23T18:01:00.329+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-11-23T18:00:58.230597+00:00', '--job-id', '654', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmp5k396j_0']
[2023-11-23T18:01:00.334+0000] {standard_task_runner.py:85} INFO - Job 654: Subtask load_to_bq_task
[2023-11-23T18:01:00.481+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-11-23T18:00:58.230597+00:00 [running]> on host jarvis
[2023-11-23T18:01:01.037+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T18:00:58.230597+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T18:00:58.230597+00:00'
[2023-11-23T18:01:02.372+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/curated/dag_sf_crimes_bqload.py", line 33, in load_bq_raw
    with open(source_file, "rb") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112318.csv'
[2023-11-23T18:01:02.409+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231123T180058, start_date=20231123T180100, end_date=20231123T180102
[2023-11-23T18:01:02.483+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 654 for task load_to_bq_task ([Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112318.csv'; 454893)
[2023-11-23T18:01:02.516+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-23T18:01:02.603+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
