[2023-12-04T20:40:42.725+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:32:03.211935+00:00 [queued]>
[2023-12-04T20:40:42.763+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:32:03.211935+00:00 [queued]>
[2023-12-04T20:40:42.764+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 4
[2023-12-04T20:40:42.844+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-12-04 20:32:03.211935+00:00
[2023-12-04T20:40:42.854+0000] {standard_task_runner.py:57} INFO - Started process 963833 to run task
[2023-12-04T20:40:42.860+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'manual__2023-12-04T20:32:03.211935+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmp9ip6vnb2']
[2023-12-04T20:40:42.864+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask load_to_bq_task
[2023-12-04T20:40:43.023+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task manual__2023-12-04T20:32:03.211935+00:00 [running]> on host jarvis
[2023-12-04T20:40:43.556+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T20:32:03.211935+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T20:32:03.211935+00:00'
[2023-12-04T20:42:54.171+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/dag_sf_crimes_bqload.py", line 41, in load_bq_raw
    job.result()
  File "/home/mani-dev/.local/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/mani-dev/.local/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 0; errors: 100. Please look into the errors[] collection for more details.
[2023-12-04T20:42:54.208+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231204T203203, start_date=20231204T204042, end_date=20231204T204254
[2023-12-04T20:42:54.294+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task load_to_bq_task (400 Error while reading data, error message: CSV table encountered too many errors, giving up. Rows: 0; errors: 100. Please look into the errors[] collection for more details.; 963833)
[2023-12-04T20:42:54.332+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-12-04T20:42:54.403+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
